.class public final Lcom/zipow/videobox/ptapp/IMProtos;
.super Ljava/lang/Object;
.source "IMProtos.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/zipow/videobox/ptapp/IMProtos$VipGroupList;,
        Lcom/zipow/videobox/ptapp/IMProtos$VipGroupListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$VipGroup;,
        Lcom/zipow/videobox/ptapp/IMProtos$VipGroupOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$VipGroupItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$VipGroupItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PMCOpenTeamChatInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$PMCOpenTeamChatInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsCustomizedComposeShortcuts;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsCustomizedComposeShortcutsOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CustomizedComposeShortcutItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$CustomizedComposeShortcutItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelSearchResponse;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelSearchResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelSearchResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelSearchResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelAdminInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelAdminInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMemberSearchResponse;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMemberSearchResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMemberSearchResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMemberSearchResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$AtMentionSortedListInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$AtMentionSortedListInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MentionFilterParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$MentionFilterParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$AtEventParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$AtEventParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$GroupExternalUsersInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$GroupExternalUsersInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ExternalUserInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ExternalUserInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ScheduleMeetingInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ScheduleMeetingInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMeetingAttendeeEvent;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMeetingAttendeeEventOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ScheduleMeetingOccurrencesInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ScheduleMeetingOccurrencesInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMeetingEvent;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMeetingEventOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$UpdatePersonalFolderMemberParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$UpdatePersonalFolderMemberParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$AddMemberToPersonalFolderParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$AddMemberToPersonalFolderParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CreatePersonalFolderParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$CreatePersonalFolderParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderRemoveItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderRemoveItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderInfoList;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$zGroupPersistentMeetingInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$zGroupPersistentMeetingInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MentionGroupInfoList;,
        Lcom/zipow/videobox/ptapp/IMProtos$MentionGroupInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MentionGroupInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$MentionGroupInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderItemList;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderItemListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalFolderItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsEditBotsRsp;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsEditBotsRspOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsGetBotsRsp;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsGetBotsRspOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsBotsInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatAppsBotsInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PrevewGroupInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$PrevewGroupInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$BuddyPreviewInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$BuddyPreviewInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupMoreMemberResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupMoreMemberResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupAccurateCountResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupAccurateCountResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$UcsBuddyGroupParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SignatureData;,
        Lcom/zipow/videobox/ptapp/IMProtos$SignatureDataOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$AddBuudyToGroupResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$AddBuudyToGroupResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$GroupPendingContactCallBackInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$GroupPendingContactCallBackInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmailUserInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmailUserInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$DlpPolicyEvent;,
        Lcom/zipow/videobox/ptapp/IMProtos$DlpPolicyEventOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$DlpPolicyCheckResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$DlpPolicyCheckResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$DlpPolicy;,
        Lcom/zipow/videobox/ptapp/IMProtos$DlpPolicyOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PinMessageCallBackInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$PinMessageCallBackInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PinMessageInfoList;,
        Lcom/zipow/videobox/ptapp/IMProtos$PinMessageInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PinMessageInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$PinMessageInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SyncReminderMsgRsp;,
        Lcom/zipow/videobox/ptapp/IMProtos$SyncReminderMsgRspOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ReminderInfoList;,
        Lcom/zipow/videobox/ptapp/IMProtos$ReminderInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ReminderInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ReminderInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$AllFiles;,
        Lcom/zipow/videobox/ptapp/IMProtos$AllFilesOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileWithIndex;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileWithIndexOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MeetingInfoForMessage;,
        Lcom/zipow/videobox/ptapp/IMProtos$MeetingInfoForMessageOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SubscribeRequestParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$SubscribeRequestParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SubscriptionReceivedParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$SubscriptionReceivedParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalGroupAtcionResponse;,
        Lcom/zipow/videobox/ptapp/IMProtos$PersonalGroupAtcionResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$RobotMsg;,
        Lcom/zipow/videobox/ptapp/IMProtos$RobotMsgOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalStorageTimeInterval;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalStorageTimeIntervalOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CodeAttachmentDownloadInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$CodeAttachmentDownloadInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SyncHistoryMsgInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$SyncHistoryMsgInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MUCNotifySettings;,
        Lcom/zipow/videobox/ptapp/IMProtos$MUCNotifySettingsOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MUCNotifySettingItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$MUCNotifySettingItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CrawlLinkResponse;,
        Lcom/zipow/videobox/ptapp/IMProtos$CrawlLinkResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CrawlLinkMetaInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$CrawlLinkMetaInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$RobotCommandList;,
        Lcom/zipow/videobox/ptapp/IMProtos$RobotCommandListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$RobotCommand;,
        Lcom/zipow/videobox/ptapp/IMProtos$RobotCommandOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FieldsEditParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$FieldsEditParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$EditParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$EditParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ButtonParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$ButtonParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SelectParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$SelectParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SelectItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$SelectItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SearchGroupResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$SearchGroupResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SearchGroupParam;,
        Lcom/zipow/videobox/ptapp/IMProtos$SearchGroupParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CallAvailableInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$CallAvailableInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$StarredGuidList;,
        Lcom/zipow/videobox/ptapp/IMProtos$StarredGuidListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$StarredGuidInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$StarredGuidInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$OutdatedLocalFileInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$OutdatedLocalFileInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$OutdatedLocalFileInfoList;,
        Lcom/zipow/videobox/ptapp/IMProtos$OutdatedLocalFileInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$GiphyMsgInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$GiphyMsgInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MakeGroupFailedByIBInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$MakeGroupFailedByIBInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$GroupCallBackInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$GroupCallBackInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$BuddyUserInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$BuddyUserInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$RoomDeviceInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$RoomDeviceInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$RoomEditInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$RoomEditInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatClassificationListInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatClassificationListInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatClassificationInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChatClassificationInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MakeGroupInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$MakeGroupInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MucNameList;,
        Lcom/zipow/videobox/ptapp/IMProtos$MucNameListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$zGroupProperty;,
        Lcom/zipow/videobox/ptapp/IMProtos$zGroupPropertyOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ThrCommentStates;,
        Lcom/zipow/videobox/ptapp/IMProtos$ThrCommentStatesOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ThrCommentState;,
        Lcom/zipow/videobox/ptapp/IMProtos$ThrCommentStateOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$DBExistResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$DBExistResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SessionMessageInfoMap;,
        Lcom/zipow/videobox/ptapp/IMProtos$SessionMessageInfoMapOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$SessionMessageInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$SessionMessageInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageInfoList;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiDetailInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiDetailInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiComment;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiCommentOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiCountMap;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiCountMapOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiCountInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$EmojiCountInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CommentDataResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$CommentDataResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ThreadDataResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$ThreadDataResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$CommentIndexList;,
        Lcom/zipow/videobox/ptapp/IMProtos$CommentIndexListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchMsgCtx;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchMsgCtxOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelSearchFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelSearchFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMemberSearchFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$ChannelMemberSearchFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchFileFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchFileFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchMSGFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchMSGFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageContentSearchFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageContentSearchFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageSenderFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageSenderFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageSearchResultList;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageSearchResultListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageSearchResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageSearchResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageContentSearchResponse;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageContentSearchResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$HighlightPositionItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$HighlightPositionItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileMatchInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileMatchInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileEventInfoRsp;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileEventInfoRspOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$PBXFileInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$PBXFileInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileFilterSearchResult;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileFilterSearchResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileFilterSearchResults;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileFilterSearchResultsOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileSearchFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileSearchFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$ContactSearchResponse;,
        Lcom/zipow/videobox/ptapp/IMProtos$ContactSearchResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchContactFilter;,
        Lcom/zipow/videobox/ptapp/IMProtos$LocalSearchContactFilterOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileIntegrationSessionData;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileIntegrationSessionDataOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileIntegrations;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileIntegrationsOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileIntegrationData;,
        Lcom/zipow/videobox/ptapp/IMProtos$FileIntegrationDataOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$StickerInfoList;,
        Lcom/zipow/videobox/ptapp/IMProtos$StickerInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$StickerInfo;,
        Lcom/zipow/videobox/ptapp/IMProtos$StickerInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$BuddyItem;,
        Lcom/zipow/videobox/ptapp/IMProtos$BuddyItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$IMMessage;,
        Lcom/zipow/videobox/ptapp/IMProtos$IMMessageOrBuilder;,
        Lcom/zipow/videobox/ptapp/IMProtos$MessageSrcType;
    }
.end annotation


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static registerAllExtensions(Lus/google/protobuf/ExtensionRegistryLite;)V
    .locals 0

    return-void
.end method
