.class public final Lcom/zipow/videobox/ptapp/PhoneProtos;
.super Ljava/lang/Object;
.source "PhoneProtos.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/zipow/videobox/ptapp/PhoneProtos$PhoneInteractInfoProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PhoneInteractInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxConferenceNotificationProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxConferenceNotificationProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxParticipantThirdPartyProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxParticipantThirdPartyProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxStartConferenceResponseProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxStartConferenceResponseProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxBlindTransferResponseProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxBlindTransferResponseProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxStartWarmTransferResponseProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxStartWarmTransferResponseProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxDirectCallResponseBaseProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxDirectCallResponseBaseProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCameraEffectResourceViewListProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCameraEffectResourceViewListProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCameraEffectResourceViewProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCameraEffectResourceViewProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSyncCallHistoryByLineResultProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSyncCallHistoryByLineResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXMessageContextResult;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXMessageContextResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallForwardingConfigDataProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallForwardingConfigDataProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallForwardingClientKVProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallForwardingClientKVProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSipCallSDKConfigurationProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSipCallSDKConfigurationProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxShareMemberList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxShareMemberListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxShareMemberProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxShareMemberProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxVoicemailShareRecipientList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxVoicemailShareRecipientListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxVoicemailShareRecipientProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxVoicemailShareRecipientProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxCallControlPreferenceDataList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxCallControlPreferenceDataListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxCallControlPreferenceData;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxCallControlPreferenceDataOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxDirectCallControlProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPbxDirectCallControlProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRedirectInfoProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRedirectInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRemoteMemberProtoList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRemoteMemberProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRemoteMemberProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRemoteMemberProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SIPCallOptionFeatureChangedBits;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SIPCallOptionFeatureChangedBitsOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SIPCallOptionFeatureBit;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SIPCallOptionFeatureBitOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXFeatureOptionChangedBits;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXFeatureOptionChangedBitsOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXFeatureOptionBit;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXFeatureOptionBitOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmRecordingTranscript;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmRecordingTranscriptOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmRecordingTransTimeline;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmRecordingTransTimelineOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmRecordingTransTimelineUser;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmRecordingTransTimelineUserOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPLineCallItem;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPLineCallItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPLine;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPLineOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPUsers;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPUsersOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPUser;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPUserOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionUnreadCountList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionUnreadCountListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionUnreadCount;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionUnreadCountOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageContactList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageContactListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageContact;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageContactOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallPeerDataProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallPeerDataProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallHistoryFilterDataProtoList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallHistoryFilterDataProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallHistoryFilterDataProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallHistoryFilterDataProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPVoiceMailSharedRelationshipProtoList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPVoiceMailSharedRelationshipProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPVoiceMailSharedRelationshipProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPVoiceMailSharedRelationshipProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSipLineInfoForCallerIDList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSipLineInfoForCallerIDListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSipLineInfoForCallerID;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSipLineInfoForCallerIDOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRegData;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRegDataOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPRecordingItemProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPRecordingItemProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPMediaFileItemProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPMediaFileItemProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXVoiceMailHistoryProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXVoiceMailHistoryProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXVoiceMailHistoryList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXVoiceMailHistoryListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallHistoryEmergencyInfoProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallHistoryEmergencyInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXCallHistoryProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXCallHistoryProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXCallHistoryList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXCallHistoryListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CallHistoryProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CallHistoryProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CallHistoryList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CallHistoryListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceParticipantEventListProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceParticipantEventListProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceParticipantEventProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceParticipantEventProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceNodeProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceNodeProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceParticipantProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ConferenceParticipantProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXIntercomCallUserListProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXIntercomCallUserListProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXIntercomCallUserProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXIntercomCallUserProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXUploadableParamsProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXUploadableParamsProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXVideomailParamsProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXVideomailParamsProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXUploadableProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXUploadableProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXMyGreetingProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXMyGreetingProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXVideomailProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXVideomailProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXDownloadableProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXDownloadableProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallVideomailProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallVideomailProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXCallGreetingProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$IPBXCallGreetingProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallMonitorEndpointsProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallMonitorEndpointsProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPEntityProtoList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPEntityProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmLiveTranscriptionProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmLiveTranscriptionProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmLiveTranscriptionSentenceProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmLiveTranscriptionSentenceProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPEntityProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPEntityProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallLiveTranscriptionResultProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallLiveTranscriptionResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXEmergencyNumberProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXEmergencyNumberProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PbxPlatformUserDataProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PbxPlatformUserDataProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PbxPlatformWindowsProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PbxPlatformWindowsProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PbxPlatformCallPeerProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PbxPlatformCallPeerProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXFileDownloadToken;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXFileDownloadTokenOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallE2EEResultProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallE2EEResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionMuteStatusList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionMuteStatusListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionMuteStatus;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionMuteStatusOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionEngaged;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXSessionEngagedOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXNetWorkInfoEx;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXNetWorkInfoExOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXExtension;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXExtensionOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SessionDraft;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SessionDraftOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallWarmTransferInfoProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallWarmTransferInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallQueueConfigList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallQueueConfigListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallQueueConfig;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmPBXCallQueueConfigOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallTransferDataProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallTransferDataProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallUnblockNumberParamList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallUnblockNumberParamListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallUnblockNumberParam;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallUnblockNumberParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallBlockNumberParamList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallBlockNumberParamListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallBlockNumberParam;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallBlockNumberParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallSLALineInfo;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallSLALineInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallSLAUserInfo;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallSLAUserInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ClientSettings;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ClientSettingsOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipPhoneIntegration;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipPhoneIntegrationOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CloudPBX;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CloudPBXOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$OutboundCallerIDList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$OutboundCallerIDListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXNumber;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXNumberOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallerIDProtoList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallerIDProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallerIDProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$SipCallerIDProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallNomadicLocation;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallNomadicLocationOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$NetworkInfoList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$NetworkInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$NetworkInfo;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$NetworkInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PhoneNumber;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PhoneNumberOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallMonitorInfoProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallMonitorInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPAgentStatusItemListProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPAgentStatusItemListProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPAgentStatusItemProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPAgentStatusItemProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPMonitorAgentListProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPMonitorAgentListProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPMonitorAgentProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPMonitorAgentProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmMonitorRequestDataProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmMonitorRequestDataProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRemoteMonitorInfoProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRemoteMonitorInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRegResultProto;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallRegResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallEmergencyInfo;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmSIPCallEmergencyInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallParkParam;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmCallParkParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$MessagesPageInfo;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$MessagesPageInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$DeleteMessageOutput;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$DeleteMessageOutputOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$DeleteMessageParamInput;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$DeleteMessageParamInputOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$WebFileIndex;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$WebFileIndexOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$MessageUploadFile;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$MessageUploadFileOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageInput;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageInputOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXFile;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXFileOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessage;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageSessionList;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageSessionListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageSession;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$PBXMessageSessionOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmIndicatorStatus;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$CmmIndicatorStatusOrBuilder;,
        Lcom/zipow/videobox/ptapp/PhoneProtos$ExtensionLevel;
    }
.end annotation


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static registerAllExtensions(Lus/google/protobuf/ExtensionRegistryLite;)V
    .locals 0

    return-void
.end method
