.class public final Lcom/zipow/videobox/ptapp/PTAppProtos;
.super Ljava/lang/Object;
.source "PTAppProtos.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/zipow/videobox/ptapp/PTAppProtos$BuddyDataItemProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BuddyDataItemProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbErrorOrSuccessProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbErrorOrSuccessProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbDeviceApprovedInfoProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbDeviceApprovedInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmGenerateBackupKeyErrorOrResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmGenerateBackupKeyErrorOrResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmGenerateBackupKeyResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmGenerateBackupKeyResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmDevicesToReviewForBackupKeyErrorOrResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmDevicesToReviewForBackupKeyErrorOrResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmDevicesToReviewForBackupKeyProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmDevicesToReviewForBackupKeyProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptRequestProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptRequestProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptResponseErrorOrResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptResponseErrorOrResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptResponseProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptResponseProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbCanDecryptResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ApproveFromBackupKeyReqProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ApproveFromBackupKeyReqProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ReviewIdentityAndDevicesReqProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ReviewIdentityAndDevicesReqProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmReviewIdentityAndDevicesErrorOrResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmReviewIdentityAndDevicesErrorOrResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmProvisionFirstDeviceErrorOrResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmProvisionFirstDeviceErrorOrResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmIdentityAndDevicesErrorOrResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmIdentityAndDevicesErrorOrResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmEnsureDeviceIsProvisionedErrorOrResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmEnsureDeviceIsProvisionedErrorOrResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmEnsureDeviceIsProvisionedResultProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmEnsureDeviceIsProvisionedResultProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmIdentityAndDevicesProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmIdentityAndDevicesProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ADNIdProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ADNIdProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneExtensionIdProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneExtensionIdProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneNumberIdProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneNumberIdProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$EmailIdProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$EmailIdProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmBasicUserDeviceInfoProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmBasicUserDeviceInfoProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbErrorDescProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmKbErrorDescProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmCMeetingInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZmCMeetingInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZMCChangeWBNOT;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZMCChangeWBNOTOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZMCWBOwner;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZMCWBOwnerOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$OtpNotificationInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$OtpNotificationInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$SearchInteractInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$SearchInteractInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PTInteractInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PTInteractInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$IDPSSOActionParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$IDPSSOActionParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$IDPSSOUserInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$IDPSSOUserInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UpdateBookMarkListResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UpdateBookMarkListResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BookmarkListRequestInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BookmarkListRequestInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BookmarkList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BookmarkListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BookmarkInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BookmarkInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageAuthResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageAuthResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDirectLinkResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDirectLinkResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDownloadLinkResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDownloadLinkResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDirectLinkParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDirectLinkParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDownloadLinkParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageCreateDownloadLinkParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$Download3rdStorageFileByUrlParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$Download3rdStorageFileByUrlParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UploadFileToThirdFileStorageParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UploadFileToThirdFileStorageParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageGetShareInfoResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageGetShareInfoResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageGetShareInfoParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageGetShareInfoParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageGetRootNodeInfoResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageGetRootNodeInfoResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageRootNodeInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageRootNodeInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageDeleteFileParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageDeleteFileParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageSupportedTypeFromCacheResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageSupportedTypeFromCacheResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageSupportedTypeResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageSupportedTypeResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageData;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageDataOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageBaseResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileStorageBaseResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomWorkSpaceList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomWorkSpaceListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$AudioDeviceDescriptionListProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$AudioDeviceDescriptionListProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$AudioDeviceDescriptionProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$AudioDeviceDescriptionProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$VideoDeviceDescriptionListProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$VideoDeviceDescriptionListProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$VideoDeviceDescriptionProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$VideoDeviceDescriptionProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppBillingPush;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppBillingPushOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppAccountSubscription;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppAccountSubscriptionOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppSubscription;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppSubscriptionOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppBilling;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InAppBillingOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomWorkSpace;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomWorkSpaceOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ProfileAdditionalNumberList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ProfileAdditionalNumberListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ProfileAdditionalNumber;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ProfileAdditionalNumberOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardPostMatchSessionsInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardPostMatchSessionsInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$NewMucMemberInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$NewMucMemberInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardPostRequestInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardPostRequestInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardPostInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardPostInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardSummaryInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardSummaryInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardMemberInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetCardMemberInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PZRInfoList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PZRInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PZRInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PZRInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZDeviceInfoList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZDeviceInfoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZDeviceInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZDeviceInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomIMPresenceInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomIMPresenceInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$SearchInstance;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$SearchInstanceOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MobileNotificationKey;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MobileNotificationKeyOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneRingtoneProtoList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneRingtoneProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneRingtoneProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneRingtoneProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ContactRingtoneProtoList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ContactRingtoneProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ContactRingtoneProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ContactRingtoneProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$RingtoneDataProtoList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$RingtoneDataProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$RingtoneDataProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$RingtoneDataProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UserLicenseProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UserLicenseProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MultiFactorAuth;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MultiFactorAuthOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$DetectZoomRoomResponse;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$DetectZoomRoomResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$WebLaunchedToLoginParam;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$WebLaunchedToLoginParamOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$LoginMeetingAuthProtoList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$LoginMeetingAuthProtoListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$LoginMeetingAuthProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$LoginMeetingAuthProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$NumberMatchedBuddyItemList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$NumberMatchedBuddyItemListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$NumberMatchedBuddyItem;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$NumberMatchedBuddyItemOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$GoogCalendarEventList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$GoogCalendarEventListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$GoogCalendarEvent;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$GoogCalendarEventOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$DeclineCallMessage;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$DeclineCallMessageOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ManagerInfoResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ManagerInfoResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UserProfileResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UserProfileResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$CountryCodelistProto;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$CountryCodelistProtoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$CountryCodePT;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$CountryCodePTOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MakeGroupResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MakeGroupResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileQueryResult;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$FileQueryResultOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomXMPPRoom;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomXMPPRoomOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ChangedBuddyGroups;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ChangedBuddyGroupsOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BuddyGroupMemberChangeList;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$BuddyGroupMemberChangeListOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$AllBuddyInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$AllBuddyInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$DeviceInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$DeviceInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$HomeTabInteractInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$HomeTabInteractInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$IPLocationInfo;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$IPLocationInfoOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneRegisterResponse;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$PhoneRegisterResponseOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomAccount;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$ZoomAccountOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetingParticipant;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$MeetingParticipantOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UrlActionData;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$UrlActionDataOrBuilder;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InvitationItem;,
        Lcom/zipow/videobox/ptapp/PTAppProtos$InvitationItemOrBuilder;
    }
.end annotation


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static registerAllExtensions(Lus/google/protobuf/ExtensionRegistryLite;)V
    .locals 0

    return-void
.end method
