.class public interface abstract Lcom/zipow/videobox/confapp/enums/SSB_MC_ANNOTATION_NOTIFICATION;
.super Ljava/lang/Object;
.source "SSB_MC_ANNOTATION_NOTIFICATION.java"


# static fields
.field public static final SSB_MC_ANNOTATION_NOTIFICATION_APPLE_STYLUS_DETECTED:I = 0xa

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_AUTO_SAVE:I = 0x16

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_CAN_UNDO_REDO:I = 0x4

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_CHECK_REMOVE_ALL_BY_HOST:I = 0x17

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_CHECK_RESTORE_ALL_BY_HOST:I = 0x18

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_CONTENT_SAVING_STATE:I = 0x13

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_CURRENT_WBUSER_ROLE:I = 0x1f

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_DOUBLETAP_PALETTE:I = 0x10

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_DRAW_CHANGED:I = 0x8

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_DRAW_TO_START:I = 0x9

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_FIRST_DRAW:I = 0xd

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_GET_WB_EXPORT_PATH:I = 0x1d

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_GET_WB_TEMP_PATH:I = 0x26

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_HAS_ANNOTATION:I = 0x5

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_LOCAL_DRAWIN_STATE:I = 0x6

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_PAGE_CHANGED:I = 0xe

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_RECOGNIZE_CHANGED:I = 0xf

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_RENDER_NOTIFY:I = 0x12

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_REQUEST_ANNOTATOR_NAME:I = 0xc

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_REQUEST_DOC_OBJECT_IMAGE:I = 0x1a

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_REQUEST_PAGE_PACKAGE:I = 0x19

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_ROOT_WND:I = 0x2

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_SET_MEETING_WBUSER_ROLE:I = 0x1e

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_SHUT_DOWN:I = 0x1

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_STARTED_UP:I = 0x0

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_TOOL_CHANGED:I = 0x3

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_TOOL_STATE_CHANGED:I = 0x15

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_UPDATE_TOOLBAR_UI:I = 0x11

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_ASYNC_REQUEST:I = 0x1c

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_DOC_OPENED:I = 0x21

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_MAKE_PERMANENT:I = 0x20

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_QUERY_HOST:I = 0x25

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_SAVE_RECENTLY_SHAPES:I = 0x22

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_SUB_CLOUD_WHITEBOARD_CONTENT_DONE:I = 0x23

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_WINDOW_STATE:I = 0x7

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WB_ZR_NOTIFY:I = 0x24

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_WHIETBOARD_ERROR:I = 0x1b

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_ZR_TAP_DETECTED:I = 0x14

.field public static final SSB_MC_ANNOTATION_NOTIFICATION_ZR_WINDOW_CHANGED:I = 0xb

.field public static final _SSB_MC_ANNOTATION_NOTIFICATION_ENUM_NUM_:I = 0x27
